config/routes.rb
Rails.application.routes.draw do
  $redis.set("comments", "0")
  devise_for :users
  resources :users
  get 'simple_pages/landing_page'

  resources :products do
    resources :comments
  end

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/admin'
  get 'simple_pages/index'
  get 'simple_pages/search'
  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  get 'simple_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments

  mount ActionCable.server => '/cable'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end

  def landing_page
    @products = Product.all
  end

  def admin
    if current_user
      @user = current_user.id
    else
      redirect_to orders_path
    end
  end


  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
=begin
    ActionMailer::Base.mail(from: @email,
      to: 'bohdanlaluck@hotmail.com',
      subject: "A new contact form message from #{@name}",
      body: @message).deliver_now
=end
    UserMailer.contact_form(@email, @name, @message).deliver_now
  end


end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/simple_pages/about.html.erb
  <div class="container-fluid section-start" id="about">
    <h1>About</h1>
    <h2>Finding used bikes for Berliners for over 40 years.</h2>
  </div>

app/views/simple_pages/admin.html.erb
<div class="container-fluid section-start" id="edit-product">








  <%= link_to 'Change password', edit_user_registration_path(@user), class: "btn btn-warning bottom-link" %><br>

  <%= link_to 'Show user info', user_path(@user), class: "btn btn-warning bottom-link" %><br>
<%= link_to 'Edit user info', edit_user_path(@user), class: "btn btn-success bottom-link" %><br><br>
</div>

app/views/simple_pages/contact.html.erb
<div class="container-fluid section-start" id="contact">

  <h1>Contact Us</h1>
  <%= flash[:notice] %>

<%= form_with(url:"/simple_pages/thank_you", method: "post", local: true) do |form| %>
<div class="row">
  <div class="form-group">
    <%= form.label :name, 'Name *' %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter Name", required: true %>
  </div>
  <div class="form-group">
    <%= form.label :email, 'E-mail *' %>
    <%= form.text_field :email, class: "form-control", placeholder: "Enter Email", required: true %>
  </div>
  <div class="form-group">
    <%= form.label :message, 'Message *' %>
    <%= form.text_area :message, class: "form-control", placeholder: "Enter Message", rows: 5, required: true %>
  </div>
</div>
<%= form.submit "Send", class: "form_label btn btn-primary" %>
<% end %>


</div>

app/views/simple_pages/index.html.erb
<div class="container-fluid section-start" id="index">
  <h1>Welcome to Bike Berlin</h1>
  <h2>Your source for used bikes in Berlin.</h2>
  <div>
  <%= image_tag("racebike2.jpg", class: "img-responsive my-image img") %>
  </div>
</div>

app/views/simple_pages/landing_page.html.erb
<div class="container-fluid section-start" id="index">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @products.each_with_index do |product, index| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%=index%>" class="<%= ' active' if product == @products.first%>"></li>
      <% end %>

    </ol>
    <div class="carousel-inner">

            <% @products.each do |product| %>
            <div class="carousel-item item<%= ' active' if product == @products.first %>">
              <%= image_tag(product.image_url, class: "img-fluid img-responsive image-carousel") %>

              <div class="carousel-caption d-none d-md-block">
                <p><%= product.name %></p>
              </div>
            </div>
            <% end %>

       </div>
    <a class="left carousel-control" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/simple_pages/search.html.erb
<div class="container-fluid section-start" id="contact">
  <%= form_with(url: products_path, method: 'get', local: true) do |form| %>

    <%= form.label :q, 'Search for:' %>
    <%= form.text_field :q, id: 'q', value: params[:q] %>
    <%= form.submit 'Search'  %>


  <% end %>

</div>

app/views/simple_pages/thank_you.html.erb
<div class="container-fluid section-start" id="edit-product">



  <div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->
<%= link_to 'Home', root_path, class: "btn btn-warning bottom-link" %>
</div>