config/routes.rb
Rails.application.routes.draw do
  $redis.set("comments", "0")
  devise_for :users
  resources :users
  get 'simple_pages/landing_page'

  resources :products do
    resources :comments
  end

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/admin'
  get 'simple_pages/index'
  get 'simple_pages/search'
  root 'simple_pages#landing_page'
  post 'simple_pages/thank_you'
  get 'simple_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments

  mount ActionCable.server => '/cable'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikes Berlin</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway%7CMerriweather%7CCousine">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body data-target=".navbar">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
  data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="projectName">
            <%= link_to "Bikes Berlin", root_path, class: "navbar-brand" %>
          </div> <!--end projectName -->
        </div><!-- end navbar header-->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(simple_pages_about_path) %>"><%= link_to "About", simple_pages_about_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(simple_pages_contact_path) %>"><%= link_to "Contact", simple_pages_contact_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to "Products", products_path, class: "dropdown-toggle" %></li>
            <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to "Orders", orders_path, class: "dropdown-toggle" %></li>

            <li class="<%= 'active' if current_page?(simple_pages_admin_path) %>"><%= link_to "Admin", simple_pages_admin_path, class: "dropdown-toggle" %></li>
            <li>
              <%= form_with(url: products_path, method: 'get', local: true, class: 'form-inline my-2 my-lg-0') do |form| %>


                <%= form.text_field :q, id: 'q', value: params[:q], class: 'form-control mr-sm-2'%>
                <%= form.submit 'Search', class: "btn btn-outline-success my-2 my-sm-0"   %>


              <% end %>
              </li>
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to('Login', new_user_session_path, class: "nav-link") %>
              </li>
              <% end %>
              </li>
          </ul>

        </div><!-- end navbar collapse -->
      </div><!-- end nav container-->
    </nav><!-- end navbar -->

    <% if notice %>
        <div class=imp-messages>
        <p class="notice alert alert-success" role="alert"><%= notice %></p>
      </div>
      <% end %>

      <% if alert %>
      <div class=imp-messages>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
        </div>
      <% end %>

    <%= yield %>

    <footer>
     <div class="try">
      <div class="copyright">
        <div class="text">&copy; Bike Berlin 2018
        </div>
      </div>
      <div class="resume">

        <div class="beside"><a href="http://www.bikeawayberlin.com" target="_blank">Bike A-Way</a></div>
        <div class="beside"><a href="http://www.berliner-fahrradlaeden.de/A-und-V-Second-Bike/" target="_blank">Second Bike</a></div>
        <div class="beside"><a href="https://twitter.com/bohdanlaluck1?ref_src=twsrc%5Etfw" class="twitter-follow-button"  data-show-screen-name="false" data-lang="en" data-show-count="false">Follow @bohdanlaluck1</a><script async src="https://platform.twitter.com/widgets.js" ></script></div>
        <div class="fb-like beside" data-href="http://laughing-thompson-954b7b.bitballoon.com/" data-layout="button" data-action="like" data-size="small" data-show-faces="true" data-share="false"></div>

      </div>
    </div>

  </body>
</html>